[FIX] changed back pymssql version to 2.3.10 to avoid odoo.sh error:
ERROR: Cannot install pymssql==2.3.10 and pymssql>=2.3.11 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pymssql>=2.3.11
    The user requested pymssql==2.3.10